blank_issues_enabled: false
contact_links:
  - name: 💬 Contact Me (Email/Socials)
    url: https://github.com/ilham
    about: Please reach out via my contact links on my profile README rather than opening an issue here!
